### ISSUE TITLE
Gráfica de conteo de rango de diferentes variables en el dashboard para datos cargados

### ISSUE THREAD

**Issue by Teett** [Teett/ds4a-team-62#20]
- Gráfica de conteo de rango de edades interactiva en el dashboard para datos cargados
- Si es posible incluir conteos de otras variables de interés
- Gráficas que muestren la estacionalidad del Stay_length, Admission_ALL

**Comment by jsbarriosmunal** [comment]
En [aff27c0] se agregaron nuevas funciones para hacer gráficos que devuelven objetos tipo: `<class 'plotly.graph_objs._figure.Figure'>` , para hacer pruebas en Dash.

**Comment by jsbarriosmunal** [comment]
Con las sesiones de trabajo de esta semana se comprobó la compatibilidad de las gráficas para ser incluidas en el dashboard actual. @mpalvarezc @Jeyson96 Quedo atento para adelantar más gráficas este fin de semana o de lo contrario cerramos este issue.

**Comment by jsbarriosmunal** [comment]
@mpalvarezc @Jeyson96 Debido a la cercanía del deadline cerraré este issue pues no hubo comentarios respecto a gráficas adicionales.
