### ISSUE TITLE
Diseño y programación del Menú de carga de datos en batch

### ISSUE THREAD

**Issue by Teett** [Teett/ds4a-team-62#21]
- Carga de datos para estadísticas del hospital (Datos de 1 mes)
- Carga de datos para predicción de los pacientes (Datos de los pacientes en el servicio de Urgencias en este momento)

**Comment by lfelipe94** [comment]
Menú de carga funcionando correctamente y guardando los datos en la BD de Postgresql creada por Cristian

**Comment by Teett** [comment]
Gracias! cualquier inconveniente volvemos a abrir este issue.
