### ISSUE TITLE
Diseñar cards con promedios descriptivos de las variables del hospital y ubicarlos en la pestaña Dashboard interactivos

### ISSUE THREAD

**Issue by Teett** [Teett/ds4a-team-62#22]
Las tarjetas deben incluir las siguientes variables:

- ED bed occupancy
- Inpatient_bed_occupancy
- Arrival intensity
- LAS intensity
- LWBS intensity

Estas tarjetas deben existir 2 veces cada una, una para los datos generales del hospital en 1 mes y otra para los pacientes cargados (¡los que están actualmente en el servicio!)

**Comment by lfelipe94** [comment]
@Teett  aún es necesario que hagamos 8 tarjetas o solo mostramos lo de los pacientes en el momento de carga del archivo?

**Comment by Teett** [comment]
Por simplicidad mostremos los cargados del archivo únicamente y simplemente si está por debajo/encima de un hardcut los pintamos en rojo/amarillo/verde. En esta tarea definamos unos threshold a ojo para las 5 variables.

**Comment by lfelipe94** [comment]
Listo! y quedaron 8 tarjetas con los thresholds del mes de datos del hospital y las tarjetas de los KPIs actuales
