### ISSUE TITLE
Construcción del Datafolio

### ISSUE THREAD

**Issue by Teett** [Teett/ds4a-team-62#26]
Presentación de ejemplo: https://docs.google.com/presentation/d/13Gj6Q1XqOKeN9suGobAVYfrTXWERKH7qJ7CLSY-TOMA/edit#slide=id.g8891a69099_0_17

Debe incluir: 

- Problem Statement & Background
- Resumen de: Data Wrangling & Cleaning
- Resumen de: Descriptive Analysis
- Resumen de: Model and Statistical Analysis
- Crear Conclusions & Further Work

**Comment by jsbarriosmunal** [comment]
No olvidar usar el término 'clinical decision support system' o 'clinical decision support tool' como fue sugerido por Dr. Hernández.

**Comment by Teett** [comment]
The datafolio is done!
![image](https://user-images.githubusercontent.com/46414320/177918653-dfdb96e6-ebfa-4794-b687-00bf36d7b53c.png)
