### ISSUE TITLE
Elaboración del Reporte Final

### ISSUE THREAD

**Issue by jsbarriosmunal** [Teett/ds4a-team-62#27]
Se debe presentar un reporte final. Es un entregable diferente al Datafolio, que está más enfocado al storytelling en una sola página. El informe debe incluir como mínimo:

- Introducción.
- Descripción general de la aplicación web.
- Ingeniería de datos (incluye descripciones del front-end, bases de datos y otros).
- Análisis de datos (Manejo y limipieza de conjuntos de datos, EDA, análisis estadísticos y modelación.
- Conclusiones y recomendaciones para nuevos trabajos.

**Comment by Teett** [comment]
El issue #29 se deja como una futura mejora que se le podría hacer al modelo de clasificación.

**Comment by jsbarriosmunal** [comment]
Se avanzó durante el fin de semana en la elaboración del reporte escrito final de acuerdo con el formato acordado y ya se incluyeron todos los avances que construímos en entregas pasadas y en los aportes que cada uno ha hecho en los issues. En el espacio de trabajo de mañana espero que podamos terminar las secciones pendientes.

Este es un documento con un avance parcial sujeto a cambios (el documento final y su versión editable será subido al repositorio cuando esté finalizado).

[62_Report.pdf](https://github.com/Teett/ds4a-team-62/files/9043139/62_Report.pdf)

**Comment by Teett** [comment]
With the inclusion of the Edna logo and the final conclusions / future work the report construction can be concluded.
![image](https://user-images.githubusercontent.com/46414320/177911433-14856d62-f6f3-4e5e-9bde-3265ee14f783.png)
