### ISSUE TITLE
Editar Video de Presentación Final

### ISSUE THREAD

**Issue by jsbarriosmunal** [Teett/ds4a-team-62#28]

**Comment by Teett** [comment]
Sobre este tema:

- Me ofrezco para grabar el video como tal, pero necesitamos definir juntos un script de qué vamos a decir! idealmente con base en el #26 y el #27.
- Necesitamos adicionalmente alguien que edite el video.

**Comment by Teett** [comment]
@jsbarriosmunal @Jeyson96 @mpalvarezc quedo pendiente de enviarles un video explicando el uso de la app apenas esté lista.

**Comment by Teett** [comment]
Resuelto con la presentación del video hoy por @Jeyson96
