### ISSUE TITLE
Ejercicio: balancear los subconjuntos train/test para 'admission' al 50%-50% y volver a probar los modelos de clasificación.

### ISSUE THREAD

**Issue by jsbarriosmunal** [Teett/ds4a-team-62#29]
Por sugerencia de Daniel González (TA) se podría hacer el ejercicio de balancer los subconjuntos train/test con muestreo aleatorio y probar si hay mejoras en los scores de los modelos de clasificación.

**Este es un ejercicio opcional.**

**Comment by Teett** [comment]
Este tema se deja como posible mejora a los modelos futuros. Mencionar en #27
